spring.application.name=pulse

spring.datasource.url=jdbc:postgresql://localhost:5432/pulse_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:632787}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=${JWT_SECRET:dev-secret-change-me-please-32chars-minimum-0123456789}
app.jwt.expiration-ms=86400000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

app.upload.avatar-dir=uploads/avatars
app.upload.base-url=http://localhost:8080




